default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coursesphere_development

test:
  <<: *default
  database: coursesphere_test

production:
  <<: *default
  database: coursesphere_production
  url: <%= ENV.fetch("DATABASE_URL", "") %>
  username: <%= ENV.fetch("APP_DATABASE_USERNAME", "coursesphere") %>
  password: <%= ENV.fetch("APP_DATABASE_PASSWORD", "") %>
